FROM centos:7

RUN yum install -y git rubygems make gcc ruby-devel && \
yum clean all && \
gem install --pre asciidoctor-pdf && \
gem install coderay && \
gem install rouge && \
gem install pygments.rb

ENV DATE 9-9-2015

ADD ./asciidoctor-no-watermark-theme.yml /usr/local/share/gems/gems/asciidoctor-pdf-1.5.0.alpha.9/data/themes/asciidoctor-no-watermark-theme.yml
ADD ./asciidoctor-watermark-theme.yml /usr/local/share/gems/gems/asciidoctor-pdf-1.5.0.alpha.9/data/themes/asciidoctor-watermark-theme.yml

ADD ./scripts/version.sh /version.sh
RUN chmod -v +x /version.sh

WORKDIR /paper
