FROM centos:7

RUN yum install -y git rubygems make && yum clean all && \
gem install bundler

ENV DATE 8-20-2015

RUN git clone https://github.com/asciidoctor/asciidoctor-pdf 

RUN cd asciidoctor-pdf/ && \
    bundle 

ADD ./asciidoctor-theme.yml /asciidoctor-pdf/data/themes/asciidoctor-theme.yml

WORKDIR /paper
